/*
 * Corso C++ https://github.com/egalli64/corso-cpp
 *
 * ctor / dtor on struct
 */
#include <iostream>

struct Point
{
    int x;
    int y;

    // implicit - field are not initialized
    // Point() {}

    // disallow implicit constructor
    // Point() = delete;

    // stressing that it generated by the compiler in the standard way
    // Point() = default;

    // when a ctor is present, default constructor generation is implicitly disallowed
    // Point(int test) { x = y = test; }

    // define the default ctor in a custom way, by initialization list (preferred)
    // Point() : x(0), y(0) { }

    // define the default ctor in a custom way, initializing fields in the ctor body
    // Point() { x = y = 0; }

    ~Point()
    {
        std::cout << "Point (" << x << ", " << y << ") removed\n";
    }
};

int main()
{
    // point is created on stack, implicit call to default ctor
    Point a;
    std::cout << "See default ctor to see if the point is correctly initialized: " << a.x << ' ' << a.y << '\n';
}
